# about.toml — cargo-about 0.8.4 config
# AGPL-3.0-only is accepted here so cargo-about can validate it, but the
# about.hbs template uses {{#unless (eq crate.name "vibe-attack")}} to
# exclude our own entry from the generated LICENSES.md output (D-16).
accepted = [
    "Apache-2.0",
    "MIT",
    "LGPL-2.1-only",
    "LGPL-3.0-only",
    "Unicode-3.0",
    "ISC",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "Zlib",
    "AGPL-3.0-only",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true

targets = [
    "x86_64-unknown-linux-gnu",
]
